# This workflow is to check if the compilation is successful and tests are running successfully.
name: Compile and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Testing

jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev clang ninja-build
        ninja --version

    - name: Configure with CMake Preset
      run: cmake --preset default-configure

    - name: Build with CMake Preset
      run: cmake --build --preset default-build

    - name: Test
      run: ctest --preset default-testing
